# Generated by Django 4.0.3 on 2022-04-14 03:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_alter_articlemodel_posted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='posted_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 14, 3, 20, 46, 159283, tzinfo=utc)),
        ),
    ]
