# Generated by Django 4.0.2 on 2022-04-15 02:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_alter_articlemodel_posted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='posted_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 15, 2, 27, 17, 330434, tzinfo=utc)),
        ),
    ]
